### ISSUE TITLE
No rate limiting

### ISSUE THREAD

**Issue by worr** [ComputerScienceHouse/WebDrink-2.0#56]
You can drop drinks rapidly, ad infinitum. This is probably not ideal for the hardware.

**Comment by bencentra** [comment]
https://github.com/bencentra/WebDrink-2.0/commit/075aa6f28bd78cf8f5fabfff938f9d0ab3e4b674

Did a quick first pass at rate limiting. Right now it's only there for /drops/drop. If your request is "successful" (you didn't forget any params) it'll log your call. If you try to make a second request before 30 seconds, it'll fail and tell you you've been limited.

30 seconds is probably too long, but for now it should get the job done.

**Comment by worr** [comment]
Ideally it should probably be per-machine, rather than per-user. Although, there should probably also be a rate limit per user?

**Comment by sman591** [comment]
I can't drop drinks via the web interface or iOS app. Observing the web interface, it looks like this is an issue with the rate limitation not being limited:

![webdrink](https://cloud.githubusercontent.com/assets/1441807/6672958/26247a34-cbe6-11e4-84f9-324df6a60096.gif)

Also, the request returns "200 OK", which I don't think is the case in a rate-limited situation?

30 seconds seems like a pretty long time, considering it doesn't take the machine 30 seconds to drop the drink and someone might want to drop a few drinks in one stop to the machine (I've done this before). A rate limit of a few seconds sounds more reasonable; if continually dropping is bad for the hardware, that sounds like something the hardware-side of things should address.

**Comment by bencentra** [comment]
Removed the rate limit check, will look into it when I get some time. It worked through direct API calls, but shame on me for not testing in the interface.

All calls that return my JSON return 200, which is also shame on me. A complete API revamp has been on my to-do list for a while now.

10 seconds maybe? Tell me a number and I'll set it.

**Comment by sman591** [comment]
Ah right, I must've been confusing the 200 return with something else. But still good to implement.

3 seconds?

**Comment by worr** [comment]
It could increase per drop, near-exponentially up to a limit. That way, legitimate users can drop multiple drinks (I had no idea that was a valid use case tbh), and you prevent asshats from abusing the system.

**Comment by sman591** [comment]
+1 @worr

**Comment by bencentra** [comment]
Haven't done robust testing yet, but it looks like I did it right this time with #59. Basic rate limiting prevents more than one call per N seconds. It can be improved with being able to configure it for M calls per N seconds, or doing the exponential delay increase Worr mentioned.

I'll try it out against the real drink server soon.
